server:
  port:
    8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohmarking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    #    url: jdbc:mysql://OMR-db:3306/OhMaRking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234

  redis:
    host: redis
    port: 6379
    password: 1234


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c4d316c33a36588d9c562db38a26831a
#            redirect-uri: http://k7c102.p.ssafy.io:8081/login/oauth2/code/kakao
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400

front:
#  url: http://k7c102.p.ssafy.io:3000/oauth/callback
  url: http://localhost:3000/oauth/callback

logging:
  level:
    org:
      hibernate:
        SQL: debug
