server:
  port: 8081

spring:
  application:
    name: master

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql_user:3306/ohmarking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/ohmarking?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
#    password: c102akdlsql
    password: 1234
  redis:
#    host: redis_db
    host: localhost
    port: 6379
#    password: 1234
#    password: c102fpeltm

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c4d316c33a36588d9c562db38a26831a
#            redirect-uri: http://oh-marking.com:8081/login/oauth2/code/kakao
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: 4e081be499c5d9be6491d6809a470f313b15df8fa3a493a3b0aa44c03e3d7eb6571ce312bf495bf7879a863bc1cbc346f06d5fba61f13617074d7a6d8d00fbd2
  access-token-validity-in-seconds: 43200
  refresh-token-validity-in-seconds: 86400

front:
#  url: http://oh-marking.com:3000/oauth/callback
  url: http://localhost.com:3000/oauth/callback
logging:
  level:
    org:
      hibernate:
        SQL: debug
